/*
Package api GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package api

import _ "embed"

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v *FileSystemBackend) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Backend":
			return []string{
				"地址",
			}, true
		case "UsernameOverwrite":
			return []string{
				"Overwrite username when not empty",
			}, true
		case "PasswordOverwrite":
			return []string{
				"Overwrite password when not empty",
			}, true
		case "PathOverwrite":
			return []string{
				"Overwrite path when not empty",
			}, true
		case "ExtraOverwrite":
			return []string{
				"Overwrite extra when not empty",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
