// Code generated by gengo:runtimedoc DO NOT EDIT.
package api

func (v *FileSystemBackend) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Backend":
			return []string{
				"地址",
			}, true
		case "UsernameOverwrite":
			return []string{
				"非空时覆盖用户名",
			}, true
		case "PasswordOverwrite":
			return []string{
				"非空时覆盖密码",
			}, true
		case "PathOverwrite":
			return []string{
				"非空时覆盖路径",
			}, true
		case "ExtraOverwrite":
			return []string{
				"非空时覆盖 extra 查询参数",
			}, true

		}

		return nil, false
	}
	return []string{
		"根据端点配置并初始化文件系统后端。",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
