/*
Package ftp GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package ftp

func (v *Config) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{}, true
		case "TLS":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *Pool) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Addr":
			return []string{}, true
		case "Auth":
			return []string{}, true
		case "ConnectTimeout":
			return []string{}, true
		case "EnableDebug":
			return []string{}, true
		case "ExplicitTLS":
			return []string{}, true
		case "TLSConfig":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *TLS) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CertData":
			return []string{}, true
		case "KeyData":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
