/*
Package csidriver GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package csidriver

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Driver) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{}, true
		case "NodeID":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v DriverContext) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "VendorVersion":
			return []string{}, true
		case "NodeID":
			return []string{}, true
		case "ControllerServiceCapabilities":
			return []string{}, true
		case "VolumeCapabilityAccessModes":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
