// Code generated by gengo:runtimedoc DO NOT EDIT.
package testutil

func (v *Benchmark) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "BigFileSize":
			return []string{}, true
		case "SmallFileCount":
			return []string{}, true
		case "Workspace":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (*CharFill) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (*FileSize) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
