/*
Package units GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package units

func (*BinarySize) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"标准单位",
		"",
		"See: http://en.wikipedia.org/wiki/Binary_prefix",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
