/*
Package ftp GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package ftp

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v ClientDriver) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Fs":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.Fs, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v Server) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Addr":
			return []string{}, true
		case "PublicHost":
			return []string{}, true
		case "DisableMLST":
			return []string{}, true
		case "DisableMLSD":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
