/*
Package main GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package main

func (v *CSIDriver) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Otel":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.Driver, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"Serve CSIDriver",
	}, true
}

func (v *Ftp) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Otel":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.FileSystemBackend, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Server, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"Serve Webdav as fuse fs",
	}, true
}

func (v *Mount) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Otel":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.Mounter, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"as fuse fs",
	}, true
}

func (v *Mounter) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "MountPoint":
			return []string{}, true
		case "Backend":
			return []string{}, true
		case "Foreground":
			return []string{}, true
		case "Delegate":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *WebDAV) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Otel":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.WebDAVServer, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"Serve Webdav as fuse fs",
	}, true
}

func (v *WebDAVServer) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Addr":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.FileSystemBackend, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
